### ISSUE TITLE
More intuitive user interface when selecting an unit

### ISSUE THREAD

**Issue by JoaoMarcosCSilva** [glest/glest-source#204]
I've realized the game has some serious UI problems.
For example, the following buttons all look exactly the same and are all mixed and scattered around a huge button list for each unit:

- the buttons for giving them an order (move, attack, etc.)
- the buttons for making them evolve themselves (like the magic golem)
- the buttons for making them unlock upgrades (like the blacksmith)
- the button for making them summon other units (like the summoner or the main teepe)
- the button for setting a meeting point

It's extremely unintuitive and it makes it much harder to learn a new faction.
What do you think about reshaping the selected unit screen, so that it gets more organized? We could split these buttons in different categories, with sub-menus or something like that.

**Comment by KeithSammut** [comment]
But how do you suggest we fix this?

**Comment by JoaoMarcosCSilva** [comment]
Well, I'm not sure.
We could use some kind of sub-menu and split that screen into summon/research/order sections, but I'm not sure how that would work.

**Comment by KeithSammut** [comment]
could you design what you have in mind please?

**Comment by JoaoMarcosCSilva** [comment]
First and foremost, unless there's a good reason not to, the "Attack", "Move" "Harvest Resources" buttons should be removed. That's because we can easily perform those actions using the mouse buttons, so there's no need for them to be in that unit selection screen.
So we're left with building, upgrading (or researching), summoning, morphing and meeting point buttons. Right now they're all in the same list, but we could separate them. So, for example, an unit screen would be like this:

Unit name
HP: 000
Armor: 000

Actions
[Repair] [Heal]

Morphing
[Morph into A] [Morph into B]

Building
[Build building X]

Researching
[Research technology T]

Summoning
[Set meeting point] [Summon minion M1] [Summon minion M2]

**Comment by andy5995** [comment]
Hmm.. I've never heard this as a problem before in MG or ZG, but as a general rule, feedback from 1 person means that 7 other people feel the same way.

When I remember first learning, I had trouble remembering where to get upgrades from, but then as I practiced a faction a few more times, it became very easy.

> the buttons for making them evolve themselves (like the magic golem)

That's available by clicking on the golem, so I don't understand why it's not intuitive.

> the buttons for making them unlock upgrades (like the blacksmith)

Every button available when clicking on the blacksmith is an upgrade.

> the button for setting a meeting point

This is usually not even needed. When a building is selected, right-clicking a location sets the meeting point. However, on mobile units there is a bug filed https://github.com/ZetaGlest/zetaglest-source/issues/192

The icons themselves are now always clear on what they do, this is why tooltips are used, the info on the lower right-hand side. Does that text appear to you, and is it translated to your native language? One option we may need to look at more is setting the default "Allow Translated Tech Trees". That's available from the game set-up menu, but hosts never check the box. While we haven't updated translations for a while, we haven't added or changed much for that part of the game.

I added a commit to the web site that will hopefully address part of your concerns 

https://github.com/andy5995/zetaglest.github.io/commit/1a73925efc7d19ad56e172f8635b1a651af9b185

As a web page:
https://zetaglest.github.io/docs/tips_for_beginners.html

**Comment by andy5995** [comment]
I think @JoaoMarcosCSilva has the advantage of offering fresh eyes and a unique perspective versus some of us who are so used to the way things have been in MegaGlest for so many years (3 for me).

After thinking about this more, I realized some changes are needed. But we'll have to make individual tickets with specific suggestions to move forward on it. And any changes are not likely to happen before the first release. Here are some screenshots from the [0 A.D. project](https://play0ad.com/) that might be inspiring:

When the main building is selected, a console appears in front of the user. 2 upgrades are shown in the lower right-hand corner (disabled because requirements aren't met yet). When you click on the map, the console goes away, the mini-map stays visible.

![image](https://user-images.githubusercontent.com/16764864/45922130-6c34d980-be89-11e8-81b8-282e9c6f8eed.png)

Hovering the mouse over an upgrade provides a detailed description, shows the cost, and shows what is needed to meet the cost. (note the food and wood at the bottom. It decreases dynamically as more resources are mined.)

![screenshot_2018-09-22_17-09-37](https://user-images.githubusercontent.com/16764864/45922169-596ed480-be8a-11e8-895e-fbc089f4ba74.png)

**Comment by mathusummut** [comment]
Will be closed until future reference.
