### ISSUE TITLE
Please upload to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [glest/glest-source#299]
Please upload https://drive.google.com/file/d/1vi4SdX97y_xjZ-8EQTf7n62jugkTqROc/view?usp=sharing to GitHub Releases, thank you. This will make it possible to test the AppImage and eventually include it in directories like https://appimage.github.io/.

**Comment by Jammyjamjamman** [comment]
Hi! We may have a problem with releasing on github because of the filesize (>500MB), but I'm not really sure because I haven't tried publishing a project release myself. Admittedly google drive is a very ugly solution xD.

I'll also mention our linux builds are still very experimental (we should point this out in the readmes). The current builds aren't suitable for deploying because the game crashes if it can't find a game data directory in the user's home.

Ps. thanks for stopping by and for the linuxdeploy software, it's awesome! Hopefully we'll have a good appimage ready soon.

**Comment by mathusummut** [comment]
It is added now to https://github.com/glest/glest-source/releases/tag/2.0 and will be updated in due time.

**Comment by probonopd** [comment]
Thank you. However, it is built on a system that is newer than the oldest still-supported distributions, which makes it impossible to run on any but the newest target systems. 

```
libc.so.6: version 'GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-8455/AppRun)
```

Any chance you could build it on trusty or xenial, e.g., using Travis CI? Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1491#issuecomment-485417965

**Comment by Jammyjamjamman** [comment]
I've added stuff to .travis.yaml to try and build and deploy an appimage. This should build glest on trusty tahr.

**Comment by Jammyjamjamman** [comment]
https://github.com/glest/glest-source/releases/tag/continuous we're publishing continuous releases using travis and some of your script-stuffs.
